storeDir: ./.pnpm-store
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-api-gateway@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-brand@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-client-connection@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-client-store@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-client-ui-conversation@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-client-ui-primitives@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-client-ui-settings@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-credentials@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-deque@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-remote-mock@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-scope@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-storage-domain@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-storage@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-timeout@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-typert-protocol@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-typert-registry@0.2.1-alpha.2'
  - '@deepseek-ai/dsh-util-workspace-path@0.2.1-alpha.2'
  - '@deepseek-ai/cordis@4.0.5-alpha.1'
  - '@deepseek-ai/cosmokit@1.8.6-alpha.1'
  - '@deepseek-ai/schemastery@3.18.5-alpha.1'
